# app/crud/user_types.py
# This file contains CRUD (Create, Read, Update, Delete) operations for UserTypeOption entities,
# interacting directly with the MySQL database via SQLAlchemy.

# Standard library imports
import uuid
from typing import Optional, List
import logging # Import logging for debug output

# SQLAlchemy imports
from sqlalchemy.orm import Session
from sqlalchemy import exc, select # Added 'select' for modern SQLAlchemy queries

# Application-specific imports
# CORRECTED: Import UserTypeOption from its dedicated model file
from app.models.user_type_option import UserTypeOption
from app.schemas.user_type_schemas import UserTypeOptionCreate, UserTypeOptionUpdate, UserTypeOptionResponse

# Configure logging for this module
logger = logging.getLogger(__name__)

# --- CRUD Operations for UserTypeOption ---

def get_user_type_option(db: Session, user_type_id: str) -> Optional[UserTypeOption]:
    """
    Retrieves a single UserTypeOption from the database by its ID.
    """
    logger.debug(f"Attempting to retrieve UserTypeOption with ID: {user_type_id}")
    # Using select for modern SQLAlchemy queries
    return db.scalar(select(UserTypeOption).filter(UserTypeOption.id == user_type_id))

def get_user_type_option_by_name(db: Session, name: str) -> Optional[UserTypeOption]:
    """
    Retrieves a single UserTypeOption from the database by its name.
    """
    logger.debug(f"Attempting to retrieve UserTypeOption with name: {name}")
    # Using select for modern SQLAlchemy queries
    return db.scalar(select(UserTypeOption).filter(UserTypeOption.name == name))

def get_all_user_type_options(db: Session, skip: int = 0, limit: int = 100) -> List[UserTypeOption]:
    """
    Retrieves all UserTypeOptions from the database.
    """
    logger.debug(f"Attempting to retrieve all UserTypeOptions (skip={skip}, limit={limit})")
    # Using select for modern SQLAlchemy queries
    return db.scalars(select(UserTypeOption).offset(skip).limit(limit)).all()

def create_user_type_option(db: Session, user_type: UserTypeOptionCreate) -> UserTypeOption:
    """
    Creates a new UserTypeOption in the database.
    """
    logger.debug(f"Attempting to create UserTypeOption with name: {user_type.name}")
    db_user_type = UserTypeOption(
        # ID is generated by default, no need to pass it explicitly
        name=user_type.name,
        description=user_type.description,
        is_active=user_type.is_active
    )
    try:
        db.add(db_user_type)
        db.commit()
        db.refresh(db_user_type)
        logger.info(f"Successfully created UserTypeOption with ID: {db_user_type.id}")
        return db_user_type
    except exc.IntegrityError as e:
        db.rollback()
        # Check for duplicate name error (specific to unique constraints)
        if "Duplicate entry" in str(e) and "'name'" in str(e):
            logger.error(f"IntegrityError: UserTypeOption with name '{user_type.name}' already exists.")
            raise ValueError(f"UserTypeOption with name '{user_type.name}' already exists.")
        logger.error(f"Error creating UserTypeOption {user_type.name}: {e}", exc_info=True)
        raise # Re-raise for controller to handle
    except Exception as e:
        db.rollback()
        logger.error(f"Unexpected error creating UserTypeOption {user_type.name}: {e}", exc_info=True)
        raise # Re-raise for controller to handle

def update_user_type_option(db: Session, user_type_id: str, user_type_update: UserTypeOptionUpdate) -> Optional[UserTypeOption]:
    """
    Updates an existing UserTypeOption in the database.
    """
    logger.debug(f"Attempting to update UserTypeOption with ID: {user_type_id}")
    # Using select for modern SQLAlchemy queries
    db_user_type = db.scalar(select(UserTypeOption).filter(UserTypeOption.id == user_type_id))
    if db_user_type:
        # Update fields that are provided in the update schema
        update_data = user_type_update.model_dump(exclude_unset=True)
        for key, value in update_data.items():
            setattr(db_user_type, key, value)
        try:
            db.commit()
            db.refresh(db_user_type)
            logger.info(f"Successfully updated UserTypeOption with ID: {db_user_type.id}")
            return db_user_type
        except exc.IntegrityError as e:
            db.rollback()
            if "Duplicate entry" in str(e) and "'name'" in str(e):
                logger.error(f"IntegrityError: UserTypeOption with name '{user_type_update.name}' already exists during update.")
                raise ValueError(f"UserTypeOption with name '{user_type_update.name}' already exists.")
            logger.error(f"Error updating UserTypeOption {user_type_id}: {e}", exc_info=True)
            raise
        except Exception as e:
            db.rollback()
            logger.error(f"Unexpected error updating UserTypeOption {user_type_id}: {e}", exc_info=True)
            raise
    logger.warning(f"UserTypeOption with ID {user_type_id} not found for update.")
    return None

def delete_user_type_option(db: Session, user_type_id: str) -> bool:
    """
    Deletes a UserTypeOption from the database by its ID.
    """
    logger.debug(f"Attempting to delete UserTypeOption with ID: {user_type_id}")
    # Using select for modern SQLAlchemy queries
    db_user_type = db.scalar(select(UserTypeOption).filter(UserTypeOption.id == user_type_id))
    if db_user_type:
        try:
            db.delete(db_user_type)
            db.commit()
            logger.info(f"Successfully deleted UserTypeOption with ID: {user_type_id}")
            return True
        except Exception as e:
            db.rollback()
            logger.error(f"Error deleting UserTypeOption {user_type_id}: {e}", exc_info=True)
            raise
    logger.warning(f"UserTypeOption with ID {user_type_id} not found for deletion.")
    return False