"""Rename updated_at to last_updated_at in users table

Revision ID: 0f5bd5ed5e31
Revises: ae217daf2e67
Create Date: 2025-06-11 04:14:36.895736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from app.models.user import UserRole # Import UserRole if your model uses it and it's needed for the column type

# revision identifiers, used by Alembic.
revision = '0f5bd5ed5e31'
down_revision = 'ae217daf2e67' # Keep your existing down_revision here
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'updated_at',
        new_column_name='last_updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False, # Based on DESCRIBE users; it was NOT NULL
        existing_nullable=False,
        server_default=func.now(), # Ensure server_default is set for creation/initial population
        existing_server_default=sa.text('CURRENT_TIMESTAMP') # Reflect existing default if any
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'last_updated_at',
        new_column_name='updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        existing_nullable=False,
        server_default=sa.text('CURRENT_TIMESTAMP'), # Revert to original default
        existing_server_default=func.now() # Reflect the default we set in upgrade
    )
    # ### end Alembic commands ###