# Mako template for a new Alembic revision script

"""
Detect schema changes

Revision ID: 1ba0df194e4b
Revises: 7dd7e3aea706
Create Date: 2025-06-25 10:10:11.815046

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sys # Import sys for debugging prints


# revision identifiers, used by Alembic.
revision = '1ba0df194e4b'
down_revision = '7dd7e3aea706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Table 'user_user_types' already exists in the database as per DESCRIBE.
    # Its creation is commented out. We will handle its foreign keys explicitly.
    # op.create_table('user_user_types',
    #     sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    #     sa.Column('user_type_option_id', mysql.CHAR(length=36), nullable=False),
    #     sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    #     sa.ForeignKeyConstraint(['user_type_option_id'], ['user_type_options.id'], ),
    #     sa.PrimaryKeyConstraint('user_id', 'user_type_option_id')
    # )

    # STEP 1: Drop foreign key constraints AND related indexes that depend on columns being altered.
    # Only dropping those confirmed to exist by SHOW CREATE TABLE / INFORMATION_SCHEMA.
    # affiliate_clicks_ibfk_1 and minted_memorial_entries_ibfk_1 confirmed NOT to exist.
    # fk_users_referring_affiliate_id_users confirmed NOT to exist as a foreign key constraint.

    # Drop foreign key from 'user_user_types' that references 'users.id'.
    print("DEBUG: Attempting to drop foreign key 'user_user_types_ibfk_1'.", file=sys.stderr)
    op.drop_constraint('user_user_types_ibfk_1', 'user_user_types', type_='foreignkey')
    # Drop foreign key from 'user_user_types' that references 'user_type_options.id'.
    print("DEBUG: Attempting to drop foreign key 'user_user_types_ibfk_2'.", file=sys.stderr)
    op.drop_constraint('user_user_types_ibfk_2', 'user_user_types', type_='foreignkey')

    # Drop associated indexes from user_user_types for robustness, if they exist
    op.drop_index(op.f('ix_user_user_types_user_id'), table_name='user_user_types', if_exists=True)
    op.drop_index(op.f('ix_user_user_types_user_type_option_id'), table_name='user_user_types', if_exists=True)


    # STEP 2: Alter existing columns' types.
    # No alteration needed for 'user_type_options.id' as it's already CHAR(36) in DB.
    # op.alter_column('user_type_options', 'id',
    #            existing_type=mysql.INTEGER(display_width=11),
    #            type_=mysql.CHAR(length=36),
    #            existing_nullable=False,
    #            postgresql_using='id::character varying(36)')

    # Alter users.id from VARCHAR(36) to CHAR(36)
    print("DEBUG: Altering column 'users.id'.", file=sys.stderr)
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False,
               postgresql_using='id::character varying(36)') # This is for PostgreSQL, safe for MySQL but not needed


    # Alter other users table columns (these were autogenerated and seem correct)
    op.alter_column('users', 'profile_picture_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'affiliate_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=True)
    print("DEBUG: Altered other columns in 'users' table.", file=sys.stderr)


    # STEP 3: Recreate foreign key constraints and indexes that were dropped.
    # Recreate the foreign key for users.referring_affiliate_id, now that 'users.id' is CHAR(36)
    # The 'fk_users_referring_affiliate_id_users' constraint was found to be just an INDEX, not a FK CONSTRAINT.
    # If your model implies it should be a FK, Alembic might add a new one with a different auto-generated name later,
    # or you might need to add it explicitly with op.create_foreign_key if your model defines it.
    # For now, we are skipping trying to drop/recreate it by its old name.
    # The original autogenerated script had:
    # op.drop_index(op.f('fk_users_referring_affiliate_id_users'), table_name='users', if_exists=True)
    # op.create_foreign_key(None, 'users', 'users', ['referring_affiliate_id'], ['affiliate_id'])
    # Keeping this pair for now, but will monitor if it causes issues or if a more explicit name is needed.

    # Recreate foreign keys on 'user_user_types' table.
    print("DEBUG: Re-creating foreign keys on 'user_user_types'.", file=sys.stderr)
    op.create_foreign_key('user_user_types_ibfk_1', 'user_user_types', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_user_types_ibfk_2', 'user_user_types', 'user_type_options', ['user_type_option_id'], ['id'])
    # Recreate associated indexes
    op.create_index(op.f('ix_user_user_types_user_id'), 'user_user_types', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_user_types_user_type_option_id'), 'user_user_types', ['user_type_option_id'], unique=False)


    # STEP 4: Add new tables (this was previously commented out as the table already existed.)
    # For now, keeping it commented based on previous "Table already exists" error.
    # op.create_table('user_user_types',
    # sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    # sa.Column('user_type_option_id', mysql.CHAR(length=36), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ), # users.id is now CHAR(36)
    # sa.ForeignKeyConstraint(['user_type_option_id'], ['user_type_options.id'], ), # user_type_options.id is now CHAR(36)
    # sa.PrimaryKeyConstraint('user_id', 'user_type_option_id')
    # )
    # print("DEBUG: Created table 'user_user_types'.", file=sys.stderr)

    # Re-creating affiliate_clicks_ibfk_1 and minted_memorial_entries_ibfk_1
    # based on their original detection by autogenerate, now that users.id is CHAR(36).
    # These were NOT found during INFO_SCHEMA query, implying they might have been created
    # by a previous migration but then dropped manually or implicitly.
    # If your models expect these, re-add them here.
    # Based on the original autogenerated script detecting them, it's safer to re-add.
    print("DEBUG: Re-creating foreign key 'affiliate_clicks_ibfk_1'.", file=sys.stderr)
    op.create_foreign_key('affiliate_clicks_ibfk_1', 'affiliate_clicks', 'users', ['affiliate_id'], ['id'], ondelete='CASCADE')

    print("DEBUG: Re-creating foreign key 'minted_memorial_entries_ibfk_1'.", file=sys.stderr)
    op.create_foreign_key('minted_memorial_entries_ibfk_1', 'minted_memorial_entries', 'users', ['minter_user_id'], ['id'])
    # Recreate index on minted_memorial_entries.minter_user_id (if needed)
    op.create_index(op.f('ix_minted_memorial_entries_minter_user_id'), 'minted_memorial_entries', ['minter_user_id'], unique=False)

    # REMOVED: STEP 5: Add missing columns to minted_memorial_entries (metadata_uri, xrpl_response)
    # These columns already exist as per DESCRIBE, so attempting to add them causes "Duplicate column name" error.
    # op.add_column('minted_memorial_entries', sa.Column('metadata_uri', sa.String(length=512), nullable=True))
    # op.add_column('minted_memorial_entries', sa.Column('xrpl_response', sa.String(length=4096), nullable=True))


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrade order is reverse of upgrade

    # REMOVED: Drop columns added in upgrade (as they are no longer added in upgrade)
    # op.drop_column('minted_memorial_entries', 'xrpl_response')
    # op.drop_column('minted_memorial_entries', 'metadata_uri')

    # Drop the re-created foreign keys from upgrade
    op.drop_constraint('affiliate_clicks_ibfk_1', 'affiliate_clicks', type_='foreignkey', if_exists=True)
    op.drop_constraint('minted_memorial_entries_ibfk_1', 'minted_memorial_entries', type_='foreignkey', if_exists=True)
    op.drop_index(op.f('ix_minted_memorial_entries_minter_user_id'), table_name='minted_memorial_entries', if_exists=True)


    # Drop new foreign keys and indexes on user_user_types
    op.drop_constraint('user_user_types_ibfk_1', 'user_user_types', type_='foreignkey', if_exists=True)
    op.drop_constraint('user_user_types_ibfk_2', 'user_user_types', type_='foreignkey', if_exists=True)
    op.drop_index(op.f('ix_user_user_types_user_id'), table_name='user_user_types', if_exists=True)
    op.drop_index(op.f('ix_user_user_types_user_type_option_id'), table_name='user_user_types', if_exists=True)

    # Then drop the user_user_types table itself (if it was originally created by this migration).
    # Since it was found to exist prior, this drop means we fully revert its *existence* if rolling back past this point.
    op.drop_table('user_user_types')


    # Revert users column types (in reverse order of upgrade changes)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('users', 'affiliate_id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'permissions_level',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('users', 'profile_picture_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)


    # Revert user_type_options.id (This was commented out in upgrade, so no downgrade needed for type)
    # If the original state before autogenerate was INT, and it was implicitly changed to CHAR(36) outside Alembic,
    # and you need to revert it back to INT during downgrade, then uncomment this.
    # As per DESCRIBE, it's already CHAR(36).
    # op.create_index(op.f('ix_user_type_options_id'), 'user_type_options', ['id'], unique=False)
    # op.alter_column('user_type_options', 'id',
    #            existing_type=mysql.CHAR(length=36),
    #            type_=mysql.INTEGER(display_width=11),
    #            existing_nullable=False)


    # Re-create original foreign key (if it existed before and was dropped in a previous implicit step)
    # As per SHOW CREATE TABLE, 'fk_users_referring_affiliate_id_users' was only an index, not a FK constraint.
    # So we should only re-create the index.
    op.create_index(op.f('fk_users_referring_affiliate_id_users'), 'users', ['referring_affiliate_id'], unique=False)

    # ### end Alembic commands ###
