# Mako template for a new Alembic revision script

"""
Create activity_logs table

Revision ID: 2328440120a3
Revises: 55359d8c0c20
Create Date: 2025-07-02 17:13:14.739936

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2328440120a3'
down_revision = '55359d8c0c20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###