"""Add missing columns to minted_memorial_entries

Revision ID: 3af0b1d93aa3
Revises: f44caa5b932a
Create Date: 2025-06-01 00:55:50.077245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# This line was causing the KeyError. It should only be in alembic/env.py.
# fileConfig(config.config_ini_section) # COMMENTED OUT: Remove or comment out this line

# revision identifiers, used by Alembic.
revision: str = '3af0b1d93aa3'
down_revision: Union[str, None] = 'f44caa5b932a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to minted_memorial_entries
    op.add_column('minted_memorial_entries', sa.Column('qr_code_image_url', sa.String(length=1024), nullable=True))
    op.add_column('minted_memorial_entries', sa.Column('ar_model_url', sa.String(length=1024), nullable=True))
    op.add_column('minted_memorial_entries', sa.Column('nft_token_id', sa.String(length=255), nullable=True))
    op.add_column('minted_memorial_entries', sa.Column('minting_transaction_hash', sa.String(length=255), nullable=True))
    op.add_column('minted_memorial_entries', sa.Column('status', sa.Enum('PENDING', 'MINTED', 'FAILED', name='mintingstatus'), nullable=False, server_default='PENDING'))
    # Ensure created_at and updated_at have proper defaults if they didn't
    # These were previously handled by direct SQL, but if this migration was meant to add them, it should reflect here.
    op.add_column('minted_memorial_entries', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('minted_memorial_entries', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), onupdate=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the columns in reverse order for downgrade
    op.drop_column('minted_memorial_entries', 'updated_at')
    op.drop_column('minted_memorial_entries', 'created_at')
    op.drop_column('minted_memorial_entries', 'status')
    op.drop_column('minted_memorial_entries', 'minting_transaction_hash')
    op.drop_column('minted_memorial_entries', 'nft_token_id')
    op.drop_column('minted_memorial_entries', 'ar_model_url')
    op.drop_column('minted_memorial_entries', 'qr_code_image_url')
    # ### end Alembic commands ###
