# Mako template for a new Alembic revision script

"""
Post users.id and user_type_options.id type changes cleanup

Revision ID: 3ea87c9079f3
Revises: 1ba0df194e4b
Create Date: 2025-06-25 11:13:47.095128

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '3ea87c9079f3'
down_revision = '1ba0df194e4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # This migration is a cleanup. The previous migration (1ba0df194e4b)
    # was responsible for altering column types and re-creating primary
    # foreign keys and their supporting indexes on minted_memorial_entries
    # and user_user_types. This migration should only handle discrepancies
    # that remain, primarily related to users.referring_affiliate_id's FK.

    # Drop the index on users.referring_affiliate_id.
    # Confirmed via SHOW CREATE TABLE that 'fk_users_referring_affiliate_id_users' is an index, not a FK constraint.
    # This index needs to be dropped if a new foreign key is being established for this relationship.
    op.drop_index(op.f('fk_users_referring_affiliate_id_users'), table_name='users', if_exists=True)

    # Create the new foreign key for users.referring_affiliate_id,
    # linking it to users.affiliate_id.
    op.create_foreign_key(None, 'users', 'users', ['referring_affiliate_id'], ['affiliate_id'])

    # All other drop_index and create_foreign_key/create_index operations
    # related to minted_memorial_entries and user_user_types are removed
    # from this cleanup migration because they were already handled by
    # the 1ba0df194e4b migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrade order reverses upgrade operations.

    # Drop the newly created foreign key on 'users' (auto-generated name)
    op.drop_constraint(None, 'users', type_='foreignkey', if_exists=True)

    # Re-create the original index on users.referring_affiliate_id (which was just an index, not a FK)
    op.create_index(op.f('fk_users_referring_affiliate_id_users'), 'users', ['referring_affiliate_id'], unique=False)

    # All other downgrade operations related to minted_memorial_entries and
    # user_user_types are removed as their upgrade counterparts were removed.
    # ### end Alembic commands ###
