"""Add referring_affiliate_id and refine user_types relationship

Revision ID: 405ad82dfcef
Revises: de25c5c96642
Create Date: 2025-06-01 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '405ad82dfcef'
down_revision: Union[str, None] = 'de25c5c96642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We remove these drop_index calls because 'name' index might not exist on fresh installs
    # and they were implicitly covered by the unique constraint on 'name' anyway.
    # op.drop_index(op.f('name'), table_name='user_type_options') # THIS LINE MUST BE COMMENTED OUT
    # op.drop_index(op.f('ix_user_type_options_name'), table_name='user_type_options') # THIS LINE MUST BE COMMENTED OUT
    # op.create_index(op.f('ix_user_type_options_name'), 'user_type_options', ['name'], unique=True) # THIS LINE MUST BE COMMENTED OUT
    # op.add_column('users', sa.Column('referring_affiliate_id', sa.String(length=36), nullable=True)) # THIS COLUMN ALREADY EXISTS
    # op.create_index(op.f('ix_users_referring_affiliate_id'), 'users', ['referring_affiliate_id'], unique=False) # THIS INDEX LIKELY ALREADY EXISTS
    # op.create_foreign_key(op.f('fk_users_referring_affiliate_id_users'), 'users', 'users', ['referring_affiliate_id'], ['id']) # THIS FK LIKELY ALREADY EXISTS
    # op.drop_column('users', 'user_types') # THIS COLUMN ALREADY DOES NOT EXIST, SO WE CAN'T DROP IT
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_types', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(op.f('fk_users_referring_affiliate_id_users'), 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_referring_affiliate_id'), table_name='users')
    op.drop_column('users', 'referring_affiliate_id')
    op.drop_index(op.f('ix_user_type_options_name'), table_name='user_type_options')
    op.create_index(op.f('ix_user_type_options_name'), 'user_type_options', ['name'], unique=False)
    # ### end Alembic commands ###