# Mako template for a new Alembic revision script

"""
Add referring_affiliate_id and refine user_types relationship

Revision ID: 405ad82dfcef
Revises: de25c5c96642
Create Date: 2025-06-09 22:21:21.065774

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '405ad82dfcef'
down_revision = 'de25c5c96642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='user_type_options')
    op.drop_index(op.f('ix_user_type_options_name'), table_name='user_type_options')
    op.create_index(op.f('ix_user_type_options_name'), 'user_type_options', ['name'], unique=True)
    op.add_column('users', sa.Column('referring_affiliate_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referring_affiliate_id'], ['id'])
    op.drop_column('users', 'user_types')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_types', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referring_affiliate_id')
    op.drop_index(op.f('ix_user_type_options_name'), table_name='user_type_options')
    op.create_index(op.f('ix_user_type_options_name'), 'user_type_options', ['name'], unique=False)
    op.create_index(op.f('name'), 'user_type_options', ['name'], unique=True)
    # ### end Alembic commands ###