# Mako template for a new Alembic revision script

"""
Add AffiliateClick table and relationships

Revision ID: 5097549cc222
Revises: 74110b66850c
Create Date: 2025-06-21 00:57:49.997742

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5097549cc222'
down_revision = '74110b66850c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_clicks',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('affiliate_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referer_url', sa.String(length=2048), nullable=True),
    sa.Column('click_destination_url', sa.String(length=2048), nullable=False),
    sa.Column('campaign_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('ad_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_clicks_ad_id'), 'affiliate_clicks', ['ad_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_affiliate_id'), 'affiliate_clicks', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_clicks_campaign_id'), 'affiliate_clicks', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_clicks_campaign_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_affiliate_id'), table_name='affiliate_clicks')
    op.drop_index(op.f('ix_affiliate_clicks_ad_id'), table_name='affiliate_clicks')
    op.drop_table('affiliate_clicks')
    # ### end Alembic commands ###