# Mako template for a new Alembic revision script

"""
Add activity_logs table

Revision ID: 55359d8c0c20
Revises: fc30a31db6a2
Create Date: 2025-07-02 16:15:14.064317

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55359d8c0c20'
down_revision = 'fc30a31db6a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed explicit op.drop_constraint calls as the database indicates
    # these foreign keys no longer exist or are handled implicitly by table drop.
    # op.drop_constraint('referrals_ibfk_1', 'referrals', type_='foreignkey')
    # op.drop_constraint('referrals_ibfk_2', 'referrals', type_='foreignkey')

    # Removed explicit op.drop_index calls as they are either redundant
    # or the indexes no longer exist after foreign key removal.
    # op.drop_index(op.f('ix_referrals_referral_code_used'), table_name='referrals')
    # op.drop_index(op.f('referred_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.alter_column('content_items', 'content_type',
               existing_type=mysql.ENUM('Art', 'Music', 'Writing', 'Photography', 'Video', 'Other'),
               type_=sa.Enum('Art', 'Music', 'Writing', 'Photography', 'Video', 'Other', name='content_type_enum', native_enum=False),
               existing_nullable=False)
    op.alter_column('content_items', 'content_status',
               existing_type=mysql.ENUM('published', 'draft', 'pending', 'rejected'),
               type_=sa.Enum('published', 'draft', 'pending', 'rejected', name='content_status_enum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_items', 'content_status',
               existing_type=sa.Enum('published', 'draft', 'pending', 'rejected', name='content_status_enum', native_enum=False),
               type_=mysql.ENUM('published', 'draft', 'pending', 'rejected'),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('content_items', 'content_type',
               existing_type=sa.Enum('Art', 'Music', 'Writing', 'Photography', 'Video', 'Other', name='content_type_enum', native_enum=False),
               type_=mysql.ENUM('Art', 'Music', 'Writing', 'Photography', 'Video', 'Other'),
               existing_nullable=False)
    op.create_table('referrals',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('referred_user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('referrer_user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('referral_code_used', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('referred_at', mysql.DATETIME(), nullable=False),
    sa.Column('referral_metadata', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name=op.f('referrals_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('referrals_ibfk_2'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('referred_user_id'), 'referrals', ['referred_user_id'], unique=True)
    op.create_index(op.f('ix_referrals_referral_code_used'), 'referrals', ['referral_code_used'], unique=False)
    # ### end Alembic commands ###
