# Mako template for a new Alembic revision script

"""
Add MintedMemorialEntry table and user relationship

Revision ID: 74110b66850c
Revises: 0f5bd5ed5e31
Create Date: 2025-06-21 00:27:38.488916

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74110b66850c'
down_revision = '0f5bd5ed5e31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('minted_memorial_entries',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('memorial_entry_id', sa.String(length=255), nullable=False),
    sa.Column('nft_token_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_hash', sa.String(length=64), nullable=False),
    sa.Column('minter_user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('minted_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('image_uri', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['minter_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_hash')
    )
    op.create_index(op.f('ix_minted_memorial_entries_memorial_entry_id'), 'minted_memorial_entries', ['memorial_entry_id'], unique=True)
    op.create_index(op.f('ix_minted_memorial_entries_nft_token_id'), 'minted_memorial_entries', ['nft_token_id'], unique=True)
    op.alter_column('user_type_options', 'description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.create_index(op.f('ix_user_type_options_id'), 'user_type_options', ['id'], unique=False)
    op.alter_column('user_user_type_options_association', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='Foreign key to the users table, identifying the user associated with a user type option.',
               existing_nullable=False)
    op.alter_column('user_user_type_options_association', 'user_type_option_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='Foreign key to the user_type_options table, identifying the user type option associated with a user.',
               existing_nullable=False)
    op.alter_column('users', 'bio',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'profile_picture_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),
               nullable=False)
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_affiliate_id'), 'users', ['affiliate_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_affiliate_id'), table_name='users')
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'profile_picture_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('user_user_type_options_association', 'user_type_option_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Foreign key to the user_type_options table, identifying the user type option associated with a user.',
               existing_nullable=False)
    op.alter_column('user_user_type_options_association', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Foreign key to the users table, identifying the user associated with a user type option.',
               existing_nullable=False)
    op.drop_index(op.f('ix_user_type_options_id'), table_name='user_type_options')
    op.alter_column('user_type_options', 'description',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.drop_index(op.f('ix_minted_memorial_entries_nft_token_id'), table_name='minted_memorial_entries')
    op.drop_index(op.f('ix_minted_memorial_entries_memorial_entry_id'), table_name='minted_memorial_entries')
    op.drop_table('minted_memorial_entries')
    # ### end Alembic commands ###