# Mako template for a new Alembic revision script

"""
Add proper timestamp defaults to users table

Revision ID: 7654221ae037
Revises: 5097549cc222
Create Date: 2025-06-21 01:58:03.100449

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7654221ae037'
down_revision = '5097549cc222'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###