# Mako template for a new Alembic revision script

"""
Add referral_code_used to User model

Revision ID: 77898610f140
Revises: 94d1f7fa0d0d
Create Date: 2025-07-13 19:52:33.244922

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77898610f140'
down_revision = '94d1f7fa0d0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('minted_memorial_entries', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('minted_memorial_entries', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.alter_column('minted_memorial_entries', 'metadata_uri',
               existing_type=mysql.VARCHAR(length=512),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('minted_memorial_entries', 'description',
               existing_type=mysql.VARCHAR(length=1024),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('minted_memorial_entries', 'image_uri',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.add_column('users', sa.Column('referral_code_used', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_referral_code_used'), 'users', ['referral_code_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code_used'), table_name='users')
    op.drop_column('users', 'referral_code_used')
    op.alter_column('minted_memorial_entries', 'image_uri',
               existing_type=sa.String(length=2048),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.alter_column('minted_memorial_entries', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('minted_memorial_entries', 'metadata_uri',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=True)
    op.drop_column('minted_memorial_entries', 'last_updated_at')
    op.drop_column('minted_memorial_entries', 'created_at')
    # ### end Alembic commands ###