# Mako template for a new Alembic revision script

"""
Rename MintedMemorialEntry to NFT and update table/columns

Revision ID: 7d8c38cf9261
Revises: 9847cb3cb933
Create Date: 2025-07-16 17:51:50.158412

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d8c38cf9261'
down_revision = '9847cb3cb933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_minted_memorial_entries_memorial_entry_id', table_name='minted_memorial_entries')
    # op.drop_index('ix_minted_memorial_entries_nft_token_id', table_name='minted_memorial_entries')

    # ALL OF THESE LINES BELOW MUST BE COMMENTED OUT
    # op.create_table('nfts',
    # sa.Column('id', sa.CHAR(length=36), nullable=False),
    # sa.Column('token_id', sa.Integer(), nullable=False),
    # sa.Column('uuid', sa.CHAR(length=36), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.String(length=2048), nullable=True),
    # sa.Column('image_url', sa.String(length=512), nullable=False),
    # sa.Column('metadata_url', sa.String(length=512), nullable=True),
    # sa.Column('owner_id', sa.CHAR(length=36), nullable=False),
    # sa.Column('content_id', sa.CHAR(length=36), nullable=False),
    # sa.Column('minted_at', sa.DateTime(), nullable=False),
    # sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    # sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('uuid')
    # ) # <--- This closing parenthesis is critical and must be commented out too!
    # ### end Alembic commands ###

    # Create new indexes for the 'nfts' table
    # op.create_index(op.f('ix_nfts_content_id'), 'nfts', ['content_id'], unique=False)
    # # op.create_index(op.f('ix_nfts_owner_id'), 'nfts', ['owner_id'], unique=False)
    #op.create_index(op.f('ix_nfts_token_id'), 'nfts', ['token_id'], unique=True)
    # --- End NFT table migration ---

    # --- Start user_type_options and user_user_types table migration ---
    # These operations seem to involve dropping and recreating to reflect schema changes
    # op.drop_index(op.f('name'), table_name='user_type_options')
    # op.drop_table('user_user_types')

    # Note: If 'user_type_options' schema also changed, it would typically be dropped and recreated here.
    # The original script only had a drop_index for it.
    # If the table itself was dropped in a previous version and recreated, that would be in a different migration.

    # Recreate user_user_types in downgrade, implies it was dropped in upgrade (which is already present)
    # Recreate user_type_options in downgrade, implies it was dropped in upgrade (not explicitly dropped above, but perhaps implicitly via other migrations or manual intervention)
    # Assuming the original auto-generated script correctly handled user_type_options and user_user_types.
    # If user_type_options was explicitly dropped, it would be 'op.drop_table('user_type_options')' here.
    # The current upgrade only drops its index, then moves to content_items.

    # --- Start content_items table migration ---
    # op.add_column('content_items', sa.Column('owner_user_id', mysql.CHAR(length=36), nullable=False))
    # op.create_index(op.f('ix_content_items_owner_user_id'), 'content_items', ['owner_user_id'], unique=False)
    # op.drop_constraint(op.f('content_items_ibfk_1'), 'content_items', type_='foreignkey')
    op.create_foreign_key(None, 'content_items', 'users', ['owner_user_id'], ['id'])
    # op.drop_column('content_items', 'creator_id')
    # --- End content_items table migration ---

    # --- Start users table migration ---
    # op.add_column('users', sa.Column('has_api_access', sa.Boolean(), nullable=False))
    # op.add_column('users', sa.Column('api_key_hashed', sa.String(length=128), nullable=True))
    # op.add_column('users', sa.Column('api_key_salt', sa.String(length=64), nullable=True))
    # op.add_column('users', sa.Column('referred_by_user_id', mysql.CHAR(length=36), nullable=True))
    # op.add_column('users', sa.Column('referred_by_referral_code', sa.String(length=50), nullable=True))
    # op.alter_column('users', 'username',
    #               existing_type=mysql.VARCHAR(length=255),
    #               type_=sa.String(length=50),
    #               existing_nullable=False)
    # op.alter_column('users', 'email',
    #               existing_type=mysql.VARCHAR(length=255),
    #               type_=sa.String(length=120),
    #               existing_nullable=False)
    # op.alter_column('users', 'hashed_password',
    #               existing_type=mysql.VARCHAR(length=255),
    #               type_=sa.String(length=128),
    #               existing_nullable=False)
    # op.alter_column('users', 'role',
    #               existing_type=mysql.ENUM('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER'),
    #               type_=sa.Enum('admin', 'superuser', 'registered_user', 'affiliate', name='user_role_enum', native_enum=False),
    #               existing_nullable=False)
    # op.alter_column('users', 'profile_picture_url',
    #               existing_type=mysql.VARCHAR(length=512),
    #               type_=sa.String(length=2048),
    #               existing_nullable=True)
    # op.alter_column('users', 'social_links',
    #               existing_type=mysql.TEXT(),
    #               type_=sa.String(length=2048),
    #               existing_nullable=True)
    # op.alter_column('users', 'referral_code',
    #               existing_type=mysql.VARCHAR(length=32),
    #               type_=sa.String(length=50),
    #               existing_nullable=True)
    # op.drop_index(op.f('ix_users_affiliate_id'), table_name='users')
    # op.drop_index(op.f('ix_users_referral_code_used'), table_name='users')
    # op.create_unique_constraint(None, 'users', ['api_key_hashed'])
    # op.drop_constraint(op.f('fk_referring_affiliate_id'), 'users', type_='foreignkey')
    # op.create_foreign_key(None, 'users', 'users', ['referred_by_user_id'], ['id'])
    # op.drop_column('users', 'affiliate_id')
    # op.drop_column('users', 'full_name')
    # op.drop_column('users', 'referring_affiliate_id')
    # op.drop_column('users', 'bio')
    # op.drop_column('users', 'referral_code_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code_used', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('users', sa.Column('referring_affiliate_id', mysql.CHAR(length=36), nullable=True))
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('affiliate_id', mysql.CHAR(length=36), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_referring_affiliate_id'), 'users', 'users', ['referring_affiliate_id'], ['affiliate_id'], ondelete='SET NULL')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_referral_code_used'), 'users', ['referral_code_used'], unique=False)
    op.create_index(op.f('ix_users_affiliate_id'), 'users', ['affiliate_id'], unique=True)
    op.alter_column('users', 'referral_code',
                    existing_type=sa.String(length=50),
                    type_=mysql.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('users', 'social_links',
                    existing_type=sa.String(length=2048),
                    type_=mysql.TEXT(),
                    existing_nullable=True)
    op.alter_column('users', 'profile_picture_url',
                    existing_type=sa.String(length=2048),
                    type_=mysql.VARCHAR(length=512),
                    existing_nullable=True)
    op.alter_column('users', 'role',
                    existing_type=sa.Enum('admin', 'superuser', 'registered_user', 'affiliate', name='user_role_enum', native_enum=False),
                    type_=mysql.ENUM('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER'),
                    existing_nullable=False)
    op.alter_column('users', 'hashed_password',
                    existing_type=sa.String(length=128),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'email',
                    existing_type=sa.String(length=120),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=False)
    op.alter_column('users', 'username',
                    existing_type=sa.String(length=50),
                    type_=mysql.VARCHAR(length=255),
                    existing_nullable=False)
    op.drop_column('users', 'referred_by_referral_code')
    op.drop_column('users', 'referred_by_user_id')
    op.drop_column('users', 'api_key_salt')
    op.drop_column('users', 'api_key_hashed')
    op.drop_column('users', 'has_api_access')
    op.add_column('content_items', sa.Column('creator_id', mysql.CHAR(length=36), nullable=False))
    op.drop_constraint(None, 'content_items', type_='foreignkey')
    op.create_foreign_key(op.f('content_items_ibfk_1'), 'content_items', 'users', ['creator_id'], ['id'])
    op.drop_index(op.f('ix_content_items_owner_user_id'), table_name='content_items')
    op.drop_column('content_items', 'owner_user_id')

    # Recreate the old user_user_types and user_type_options tables
    op.create_table('user_user_types',
        sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
        sa.Column('user_type_option_id', mysql.CHAR(length=36), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_user_types_ibfk_1')),
        sa.ForeignKeyConstraint(['user_type_option_id'], ['user_type_options.id'], name=op.f('user_user_types_ibfk_2')),
        sa.PrimaryKeyConstraint('user_id', 'user_type_option_id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table('user_type_options',
        sa.Column('id', mysql.CHAR(length=36), nullable=False),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('description', mysql.VARCHAR(length=1024), nullable=True),
        sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('last_updated_at', mysql.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'user_type_options', ['name'], unique=True)


    # Drop new indexes related to 'nfts' before dropping the table
    op.drop_index(op.f('ix_nfts_token_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_owner_id'), table_name='nfts')
    op.drop_index(op.f('ix_nfts_content_id'), table_name='nfts')

    # Drop the new 'nfts' table
    op.drop_table('nfts')

    # Recreate the old 'minted_memorial_entries' table and its indexes
    op.create_table('minted_memorial_entries',
        sa.Column('id', mysql.CHAR(length=36), nullable=False),
        sa.Column('memorial_entry_id', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('nft_token_id', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('transaction_hash', mysql.VARCHAR(length=64), nullable=False),
        sa.Column('minter_user_id', mysql.CHAR(length=36), nullable=False),
        sa.Column('minted_at', mysql.DATETIME(), nullable=False),
        sa.Column('metadata_uri', mysql.MEDIUMTEXT(), nullable=True),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('description', mysql.MEDIUMTEXT(), nullable=True),
        sa.Column('image_uri', mysql.VARCHAR(length=2048), nullable=True),
        sa.Column('xrpl_response', mysql.MEDIUMTEXT(), nullable=True),
        sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=False),
        sa.Column('last_updated_at', mysql.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(['minter_user_id'], ['users.id'], name=op.f('minted_memorial_entries_ibfk_1')),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_general_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('transaction_hash'), 'minted_memorial_entries', ['transaction_hash'], unique=True)
    op.create_index(op.f('ix_minted_memorial_entries_nft_token_id'), 'minted_memorial_entries', ['nft_token_id'], unique=True)
    op.create_index(op.f('ix_minted_memorial_entries_memorial_entry_id'), 'minted_memorial_entries', ['memorial_entry_id'], unique=True)
    # ### end Alembic commands ###