# Mako template for a new Alembic revision script

"""
Add referral_code column to users table

Revision ID: 8286b81832f9
Revises: 8560a2756b59
Create Date: 2025-06-27 12:20:54.825480

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql # This import is still needed for downgrade's type conversion if using mysql.MEDIUMTEXT in downgrade, but we will remove the problematic alter_column calls

# revision identifiers, used by Alembic.
revision = '8286b81832f9'
down_revision = '8560a2756b59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed op.alter_column for 'minted_memorial_entries.xrpl_response' as it caused issues.
    # The xrpl_response column should remain MEDIUMTEXT, which is its current state
    # and what the app/models/nft.py now explicitly defines.
    op.add_column('users', sa.Column('referral_code', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referral_code')
    # Removed op.alter_column for 'minted_memorial_entries.xrpl_response' to match upgrade.
    # The xrpl_response column should remain MEDIUMTEXT.
    # ### end Alembic commands ###
