# Mako template for a new Alembic revision script

"""
Verification of complete schema synchronization

Revision ID: 8560a2756b59
Revises: f51c8e84e670
Create Date: 2025-06-25 11:40:49.621590

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8560a2756b59'
down_revision = 'f51c8e84e670'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###