# Mako template for a new Alembic revision script

"""
Update User model types for social_links and permissions_level

Revision ID: 94d1f7fa0d0d
Revises: 9326f25bfedc
Create Date: 2025-07-04 13:19:21.665429

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import app.models.user # REQUIRED: To reference app.models.user.JSONEncodedDict
from sqlalchemy import text # REQUIRED: For op.execute(text(...))

# revision identifiers, used by Alembic.
revision = '94d1f7fa0d0d'
down_revision = '9326f25bfedc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update existing string values in 'permissions_level' to their integer equivalents.
    # This is crucial and MUST happen BEFORE altering the column type to INTEGER.

    print("Attempting to update 'permissions_level' from 'standard' to 0...")
    try:
        op.execute(
            text("UPDATE users SET permissions_level = 0 WHERE permissions_level = 'standard'")
        )
        print("Successfully updated 'permissions_level' from 'standard' to 0.")
    except Exception as e:
        print(f"Warning: Could not update 'permissions_level' from 'standard' to 0. It might already be an integer or another issue occurred: {e}")

    print("Attempting to update 'permissions_level' from 'full_system_access' to 100...")
    try:
        op.execute(
            text("UPDATE users SET permissions_level = 100 WHERE permissions_level = 'full_system_access'")
        )
        print("Successfully updated 'permissions_level' from 'full_system_access' to 100.")
    except Exception as e:
        print(f"Warning: Could not update 'permissions_level' from 'full_system_access' to 100. It might already be an integer or another issue occurred: {e}")

    print("Attempting to update 'permissions_level' from 'elevated' to 50...")
    try:
        op.execute(
            text("UPDATE users SET permissions_level = 50 WHERE permissions_level = 'elevated'")
        )
        print("Successfully updated 'permissions_level' from 'elevated' to 50.")
    except Exception as e:
        print(f"Warning: Could not update 'permissions_level' from 'elevated' to 50. It might already be an integer or another issue occurred: {e}")

    # Now, alter the column types for social_links and permissions_level
    op.alter_column('users', 'social_links',
                    existing_type=mysql.VARCHAR(length=1024),
                    type_=app.models.user.JSONEncodedDict(), # References the custom type from app.models.user
                    existing_nullable=True)
    op.alter_column('users', 'permissions_level',
                    existing_type=mysql.VARCHAR(length=50),
                    type_=sa.Integer(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert column types
    op.alter_column('users', 'permissions_level',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'social_links',
               existing_type=app.models.user.JSONEncodedDict(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)

    # Revert data if necessary (e.g., if you had a specific mapping back to strings)
    # NOTE: Reverting data from int to string might be lossy if new int values were introduced.
    # For simplicity, this downgrade does not attempt to revert integer values back to specific strings.
    # If specific string values like 'standard' or 'full_system_access' are expected on downgrade,
    # you would need to add similar op.execute(text(...)) statements here.
    # ### end Alembic commands ###
