# Mako template for a new Alembic revision script

"""
Add is_verified to User model

Revision ID: 9847cb3cb933
Revises: 77898610f140
Create Date: 2025-07-14 15:24:14.158031

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9847cb3cb933'
down_revision = '77898610f140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###