# Mako template for a new Alembic revision script

"""
Rename last_updated_at to updated_at in users table

Revision ID: ae217daf2e67
Revises: f44caa5b932a
Create Date: 2025-06-11 01:57:05.789571

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'ae217daf2e67'
down_revision = 'f44caa5b932a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_user_type_options_association', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment='Foreign key to the users table, identifying the user associated with a user type option.',
               existing_nullable=False)
    op.alter_column('user_user_type_options_association', 'user_type_option_id',
               existing_type=mysql.INTEGER(),
               comment='Foreign key to the user_type_options table, identifying the user type option associated with a user.',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # Manually added: Rename last_updated_at to updated_at in users table
    op.alter_column(
        'users',
        'last_updated_at',
        new_column_name='updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('user_user_type_options_association', 'user_type_option_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Foreign key to the user_type_options table, identifying the user type option associated with a user.',
               existing_nullable=False)
    op.alter_column('user_user_type_options_association', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='Foreign key to the users table, identifying the user associated with a user type option.',
               existing_nullable=False)
    # Manually added: Rename updated_at back to last_updated_at in users table
    op.alter_column(
        'users',
        'updated_at',
        new_column_name='last_updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text('now()')
    )
    # ### end Alembic commands ###