# Mako template for a new Alembic revision script

"""
Final schema sync check (expected empty)

Revision ID: c0111eb26a9e
Revises: 8286b81832f9
Create Date: 2025-06-27 12:43:20.392496

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0111eb26a9e'
down_revision = '8286b81832f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###