# Mako template for a new Alembic revision script

"""
Final schema sync check

Revision ID: d7a5767bd91c
Revises: 3ea87c9079f3
Create Date: 2025-06-25 11:25:48.919285

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql # Ensure mysql types are available


# revision identifiers, used by Alembic.
revision = 'd7a5767bd91c'
down_revision = '3ea87c9079f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Manual adjustment to handle foreign key and index dependencies:

    # 1. Drop foreign key 'user_user_types_ibfk_2' as it relies on 'ix_user_user_types_user_type_option_id'
    # This foreign key needs to be dropped before its dependent index can be dropped.
    op.drop_constraint('user_user_types_ibfk_2', 'user_user_types', type_='foreignkey', if_exists=True)

    # 2. Now drop the index 'ix_user_user_types_user_type_option_id'
    # This was the index causing the "needed in a foreign key constraint" error.
    op.drop_index(op.f('ix_user_user_types_user_type_option_id'), table_name='user_user_types', if_exists=True)

    # 3. Create the missing foreign key on minted_memorial_entries.
    # Confirmed this FK does NOT exist in the DB, so this operation is valid.
    op.create_foreign_key(None, 'minted_memorial_entries', 'users', ['minter_user_id'], ['id'])

    # 4. Re-create the 'user_user_types_ibfk_2' foreign key and its index.
    # This ensures the relationship is correctly re-established after index drop.
    op.create_foreign_key('user_user_types_ibfk_2', 'user_user_types', 'user_type_options', ['user_type_option_id'], ['id'])
    op.create_index(op.f('ix_user_user_types_user_type_option_id'), 'user_user_types', ['user_type_option_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Downgrade operations should reverse the upgrade:

    # 1. Drop the re-created 'user_user_types_ibfk_2' foreign key and its index
    op.drop_constraint('user_user_types_ibfk_2', 'user_user_types', type_='foreignkey', if_exists=True)
    op.drop_index(op.f('ix_user_user_types_user_type_option_id'), table_name='user_user_types', if_exists=True)

    # 2. Drop the foreign key created on 'minted_memorial_entries'
    op.drop_constraint(None, 'minted_memorial_entries', type_='foreignkey', if_exists=True) # Assuming 'None' is the autogenerated name from upgrade

    # 3. Re-create the index 'ix_user_user_types_user_type_option_id' if needed for original schema
    # This might be redundant if it was part of a primary key or unique index.
    # Based on the original SHOW INDEXES, it was a non-unique index.
    op.create_index(op.f('ix_user_user_types_user_type_option_id'), 'user_user_types', ['user_type_option_id'], unique=False)

    # ### end Alembic commands ###
