"""Update user Pydantic models for referring_affiliate_id

Revision ID: de25c5c96642
Revises: c7904595d2b3
Create Date: 2025-06-01 09:45:32.913909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de25c5c96642'
down_revision: Union[str, None] = 'c7904595d2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_user_type_options_id'), 'user_type_options', ['id'], unique=False)
    op.alter_column('users', 'affiliate_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),
               nullable=False)
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_users_affiliate_id'), 'users', ['affiliate_id'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['referring_affiliate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_affiliate_id'), table_name='users')
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'affiliate_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_type_options_id'), table_name='user_type_options')
    op.drop_table('user_type_options')
    # ### end Alembic commands ###
