# Mako template for a new Alembic revision script

"""
create content items table

Revision ID: e428dd7a16f5
Revises: c0111eb26a9e
Create Date: 2025-06-28 16:59:43.817979

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e428dd7a16f5'
down_revision = 'c0111eb26a9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_affiliates_referral_code'), 'affiliates', ['referral_code'], unique=True)
    op.create_table('affiliate_commissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.String(length=36), nullable=False),
    sa.Column('referred_sale_id', sa.String(length=36), nullable=True),
    sa.Column('referred_sale_value', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('commission_date', sa.DateTime(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referred_sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_commissions')
    op.drop_index(op.f('ix_affiliates_referral_code'), table_name='affiliates')
    op.drop_table('affiliates')
    # ### end Alembic commands ###