# Mako template for a new Alembic revision script

"""
Final schema synchronization confirmation

Revision ID: f32e4687e00e
Revises: d7a5767bd91c
Create Date: 2025-06-25 11:31:43.176082

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'f32e4687e00e'
down_revision = 'd7a5767bd91c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Manual adjustment to handle foreign key and index dependencies:

    # 1. Drop foreign key 'user_user_types_ibfk_2' first, as it relies on 'ix_user_user_types_user_type_option_id'
    op.drop_constraint('user_user_types_ibfk_2', 'user_user_types', type_='foreignkey', if_exists=True)

    # 2. Now drop the index 'ix_user_user_types_user_type_option_id'
    # This was the index causing the "needed in a foreign key constraint" error.
    op.drop_index(op.f('ix_user_user_types_user_type_option_id'), table_name='user_user_types', if_exists=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Downgrade operations should reverse the upgrade:

    # 1. Re-create the index 'ix_user_user_types_user_type_option_id'
    op.create_index(op.f('ix_user_user_types_user_type_option_id'), 'user_user_types', ['user_type_option_id'], unique=False)

    # 2. Re-create the foreign key 'user_user_types_ibfk_2'
    op.create_foreign_key('user_user_types_ibfk_2', 'user_user_types', 'user_type_options', ['user_type_option_id'], ['id'])

    # ### end Alembic commands ###
