"""Add referring_affiliate_id to User model

Revision ID: f44caa5b932a
Revises: 78b39a1b30a3
Create Date: 2025-06-01 00:55:50.077245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f44caa5b932a'
down_revision: Union[str, None] = '78b39a1b30a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user_type_options', # COMMENTED OUT THIS ENTIRE BLOCK AS TABLE ALREADY EXISTS
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255), nullable=False),
    # sa.Column('description', sa.String(length=1024), nullable=True),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True) # COMMENTED OUT - INDEX ALREADY EXISTS
    # op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False) # COMMENTED OUT - INDEX ALREADY EXISTS
    # op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True) # COMMENTED OUT - INDEX ALREADY EXISTS
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_index('ix_users_affiliate_id', table_name='users')
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=sa.Integer(),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'affiliate_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # op.drop_column('users', 'updated_at') # COMMENTED OUT THIS LINE
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.alter_column('users', 'affiliate_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=True)
    op.alter_column('users', 'bio',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('users', 'referring_affiliate_id',
               existing_type=sa.String(length=36),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Enum('GUEST_PLAYER', 'REGISTERED_USER', 'CONSUMER', 'AFFILIATE', 'CREATOR', 'ADMIN', 'SUPER_USER', name='userrole'),

               nullable=True)
    op.alter_column('users', 'permissions_level',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index('ix_users_affiliate_id', 'users', ['affiliate_id'], unique=False)
    op.create_foreign_key('users_ibfk_1', 'users', 'users', ['referring_affiliate_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('user_type_options')
    # ### end Alembic commands ###