# Mako template for a new Alembic revision script

"""
Final confirmation of schema synchronization

Revision ID: f51c8e84e670
Revises: f32e4687e00e
Create Date: 2025-06-25 11:38:02.879496

"""

# IMPORTS
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51c8e84e670'
down_revision = 'f32e4687e00e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_user_types', 'user_type_options', ['user_type_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_user_types', type_='foreignkey')
    # ### end Alembic commands ###