# app/main.py

import sys
import asyncio

try:
    import bcrypt
    # These debug prints are still active from previous debugging, will keep for now
    print(f"DEBUG: sys.path at startup: {sys.path}", file=sys.stderr)
    print(f"DEBUG: Loaded bcrypt module path: {bcrypt.__file__}", file=sys.stderr)
    print(f"DEBUG: Loaded bcrypt version: {bcrypt.__version__}", file=sys.stderr)
except AttributeError:
    print("DEBUG: bcrypt module loaded, but missing __about__ attribute.", file=sys.stderr)
except ImportError:
    print("DEBUG: bcrypt module failed to import.", file=sys.stderr)
except Exception as e:
    print(f"DEBUG: An unexpected error occurred during bcrypt import: {e}", file=sys.stderr)

from fastapi import FastAPI, Depends, HTTPException, status, Request
from fastapi.security import OAuth2PasswordRequestForm, OAuth2PasswordBearer, HTTPBearer
from sqlalchemy.orm import Session
from typing import Optional, List
from pydantic import BaseModel, EmailStr, Field
import os

from .database import Base, SessionLocal, get_db, init_db

from app.models import user, affiliate, nft

from app.controllers import auth
from app.controllers import user_types
from app.controllers import admin_reports
from app.controllers import public_reports
from app.controllers import nft_operations

from fastapi.routing import APIRoute

# NEW: Define the security scheme instance
# This creates an instance of HTTPBearer which FastAPI uses to generate the OpenAPI spec
# We will use this in the API definition to explicitly tell Swagger about our bearer token.
bearer_scheme = HTTPBearer(
    description="Enter your JWT token in the format: **Bearer &lt;token>**",
    scheme_name="BearerAuth" # Assign a name that can be referenced in security
)

app = FastAPI(
    title="Guzzy and Bash Productions API",
    description="Backend API for Guzzy and Bash Productions platform, including user management, NFT minting, and reporting.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_url="/openapi.json",
    # CRITICAL FIX: Explicitly define ALL security schemes in `components.securitySchemes`
    # and then apply the desired one globally using the top-level `security` parameter.
    # This ensures that FastAPI is fully aware of all schemes and which one to prioritize.
    components={ # Define components directly at the FastAPI level
        "securitySchemes": {
            # Our custom BearerAuth scheme
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "JWT Authorization header using the Bearer scheme. Example: 'Bearer your-token-here'"
            },
            # The OAuth2PasswordBearer scheme, which is implicitly generated by FastAPI
            # when OAuth2PasswordRequestForm is used. We explicitly define it here
            # to ensure it's part of the components, and its name is consistent.
            # This is important to manage what Swagger UI ultimately presents.
            "OAuth2PasswordBearer": {
                "type": "oauth2",
                "flows": {
                    "password": {
                        "tokenUrl": "api/token",
                        "scopes": {}
                    }
                }
            }
        }
    },
    # Apply the BearerAuth scheme globally to all endpoints by default.
    # This tells Swagger which authentication method to prefer for authorized routes.
    security=[{"BearerAuth": []}]
)

# Middleware for database session management
@app.middleware("http")
async def db_session_middleware(request: Request, call_next):
    request.state.db = SessionLocal()
    try:
        response = await call_next(request)
    finally:
        request.state.db.close()
    return response

# --- Include your custom API routers here ---
app.include_router(auth.router, prefix="/api")
app.include_router(user_types.router, prefix="/api/v1")
app.include_router(admin_reports.router, prefix="/api/v1", tags=["Admin Reports"])
app.include_router(public_reports.router, prefix="/api/v1", tags=["Public Reports"])
app.include_router(nft_operations.router, prefix="/api/v1", tags=["NFT Operations"])

@app.get("/", tags=["Core"])
async def root():
    return {"message": "Welcome to Guzzy and Bash Productions API!"}

# Call init_db to create tables if they don't exist
@app.on_event("startup")
async def on_startup():
    print("DEBUG: Entered on_startup event.", file=sys.stderr)
    print(f"DEBUG: 'app' in globals(): {'app' in globals()}", file=sys.stderr)
    print(f"DEBUG: 'app' in locals(): {'app' in locals()}", file=sys.stderr)

    print("DEBUG: Registered FastAPI routes:", file=sys.stderr)
    for route in app.routes:
        if isinstance(route, APIRoute):
            print(f"DEBUG:   Path: {route.path}, Name: {route.name}, Methods: {route.methods}", file=sys.stderr)

    if asyncio.iscoroutinefunction(init_db):
        await init_db()
    else:
        init_db()
    print("SQLAlchemy Base registry configured.", file=sys.stderr)
    print("Database initialized successfully.", file=sys.stderr)

    try:
        user.UserResponse.model_rebuild(_types_namespace=globals())
        print("DEBUG: user.UserResponse.model_rebuild() successful.", file=sys.stderr)
    except Exception as e:
        print(f"ERROR: user.UserResponse.model_rebuild() failed: {e}", file=sys.stderr)
        raise

    try:
        nft.MintedMemorialEntryResponse.model_rebuild(_types_namespace=globals())
        print("DEBUG: nft.MintedMemorialEntryResponse.model_rebuild() successful.", file=sys.stderr)
    except Exception as e:
        print(f"ERROR: nft.MintedMemorialEntryResponse.model_rebuild() failed: {e}", file=sys.stderr)
        raise
