# app/controllers/affiliate_reports.py

from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session
from datetime import datetime # NEW: Import datetime for type hinting

# Import common dependencies and the User model
from app.dependencies import get_db, get_current_active_user
from app.models.user import User # Import User model for dependency type hinting
from app.schemas.user_schemas import UserRole # Import UserRole to check if user is an affiliate

# Import the reports service (will contain dummy data initially)
from app.services import reports as reports_service

# Define the APIRouter for affiliate reports
# A prefix of "/affiliate_reports" will be used
# Tags help organize documentation in Swagger UI
router = APIRouter(prefix="/affiliate_reports", tags=["Affiliate Reports"])

# Dependency to check if the current user is an active Affiliate
# This will be refined, but for now, ensures user is authenticated and has the AFFILIATE role
async def get_current_active_affiliate_user(current_user: User = Depends(get_current_active_user)):
    """
    Dependency that returns the current authenticated and active Affiliate user.
    Checks if the user's role is AFFILIATE or SUPER_USER or ADMIN (as they can often see affiliate data).
    """
    if current_user.role not in [UserRole.AFFILIATE, UserRole.ADMIN, UserRole.SUPER_USER]:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not enough permissions: Affiliate, Admin, or Superuser role required."
        )
    return current_user

# --- Affiliate-Specific Reports ---

@router.get(
    "/my-summary",
    response_model=Dict[str, Any], # Will return a dictionary of summary data
    summary="Get My Affiliate Summary (Affiliate Only)",
    description="Provides a summary of the current affiliate's performance, including total referrals, clicks, and estimated earnings. Requires Affiliate, Admin, or Superuser role.",
    tags=["Affiliate Reports"]
)
async def get_my_affiliate_summary(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_affiliate_user) # Ensures specific affiliate access
):
    """
    Retrieves a summary report for the currently authenticated affiliate user.
    """
    # Call the reports service function (will return dummy data initially)
    report_data = await reports_service.get_affiliate_summary_report_dummy(db, affiliate_id=current_user.affiliate_id)
    return report_data

@router.get(
    "/my-referrals",
    response_model=List[Dict[str, Any]], # Will return a list of referral details
    summary="Get My Referral List (Affiliate Only)",
    description="Provides a detailed list of users referred by the current affiliate. Requires Affiliate, Admin, or Superuser role.",
    tags=["Affiliate Reports"]
)
async def get_my_referral_list(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_affiliate_user),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
):
    """
    Retrieves a detailed list of users referred by the currently authenticated affiliate user.
    """
    # Call the reports service function (will return dummy data initially)
    report_data = await reports_service.get_affiliate_referrals_report_dummy(db, affiliate_id=current_user.affiliate_id, skip=skip, limit=limit)
    return report_data

@router.get(
    "/my-clicks",
    response_model=List[Dict[str, Any]], # Will return a list of click details
    summary="Get My Link Clicks Report (Affiliate Only)",
    description="Provides a detailed report on clicks generated by the current affiliate's links. Requires Affiliate, Admin, or Superuser role.",
    tags=["Affiliate Reports"]
)
async def get_my_link_clicks_report(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_affiliate_user),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    start_date: Optional[datetime] = Query(None, description="Filter clicks from this date (YYYY-MM-DD)"),
    end_date: Optional[datetime] = Query(None, description="Filter clicks up to this date (YYYY-MM-DD)"),
):
    """
    Retrieves a detailed report on link clicks generated by the currently authenticated affiliate user.
    """
    # Call the reports service function (will return dummy data initially)
    report_data = await reports_service.get_affiliate_clicks_report_dummy(db, affiliate_id=current_user.affiliate_id, skip=skip, limit=limit, start_date=start_date, end_date=end_date)
    return report_data

@router.get(
    "/my-earnings",
    response_model=Dict[str, Any], # Will return a summary of earnings
    summary="Get My Earnings Report (Affiliate Only)",
    description="Provides a summary of earnings and commission details for the current affiliate. Requires Affiliate, Admin, or Superuser role.",
    tags=["Affiliate Reports"]
)
async def get_my_earnings_report(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_active_affiliate_user),
    start_date: Optional[datetime] = Query(None, description="Filter earnings from this date (YYYY-MM-DD)"),
    end_date: Optional[datetime] = Query(None, description="Filter earnings up to this date (YYYY-MM-DD)"),
):
    """
    Retrieves an earnings report for the currently authenticated affiliate user.
    """
    # Call the reports service function (will return dummy data initially)
    report_data = await reports_service.get_affiliate_earnings_report_dummy(db, affiliate_id=current_user.affiliate_id, start_date=start_date, end_date=end_date)
    return report_data
